New Homol stage in Delivery Pipeline

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -33,7 +33,56 @@ stages:
       mkdir -p output
 
       mv export.json ./output/
-- name: IMPORT
+- name: IMPORT-HOM
+  inputs:
+  - type: job
+    stage: EXPORT
+    job: ExportWorkspace 
+  properties:
+  - name: API_BASE_URLS
+    value: ${API_BASE_URLS_HOM}
+  - name: API_KEYS
+    value: ${API_KEYS_HOM}
+    type: secure
+  jobs:    
+  - name: ImportWorkspace
+    type: tester
+    fail_stage: true
+    build_type: shell
+    enable_tests: false
+    script: |
+      #!/bin/bash
+      declare -a API_KEY_TRG
+      j=0
+      for API_KEY in $API_KEYS
+      do
+         API_KEY_TRG[j]=$API_KEY
+         j=$(( j + 1 ))
+      done
+
+      API_KEY_TRG=($API_KEYS)
+      i=0
+      for API_BASE_URL in $API_BASE_URLS
+      do
+          echo "Looking for workspace with name $WORKSPACE_NAME at $API_BASE_URL" 
+          curl -u "apikey":"${API_KEY_TRG[$i]}" "$API_BASE_URL/v1/workspaces?version=2018-09-20" > workspaces.json
+          export TARGET_WORKSPACE_ID=$(jq -r ".workspaces[] | select(.name == \"$WORKSPACE_NAME\") | .workspace_id" workspaces.json)
+
+          if [ -z "$TARGET_WORKSPACE_ID" ]
+          then
+             echo "Workspace with name $WORKSPACE_NAME not found for this instance."
+             exit 1
+          fi
+
+          echo "Target workspace ID is $TARGET_WORKSPACE_ID"
+          echo "Importing workspace $TARGET_WORKSPACE_ID..."
+          
+          curl -H "Content-Type: application/json" -X POST -d @export.json -u "apikey":"${API_KEY_TRG[$i]}" "$API_BASE_URL/v1/workspaces/$TARGET_WORKSPACE_ID?version=2018-09-20"
+          i=$(( i + 1))
+      done
+      echo "Finished deploy!"
+
+- name: IMPORT-PROD
   inputs:
   - type: job
     stage: EXPORT
